services:
  keiko:
    image: ghcr.io/pixelaw/keiko:0.1.3
    container_name: keiko
    ports:
      - "5050:5050"
      - "3000:3000"
      - "8080:8080"
      - "50051"
    restart: unless-stopped
    volumes:
      - ./contracts:/keiko/contracts
    networks:
      - pixelaw

networks:
  pixelaw:
    driver: bridge

