services:
  keiko:
    image: ghcr.io/pixelaw/keiko:latest
    container_name: keiko
    command: ["./keiko", "--disable-validate", "--disable-fee"]
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:5050:5050"
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    volumes:
      - ./contracts/genesis_template.json:/keiko/config/genesis.json
      - ./contracts/target/dev/manifest.json:/keiko/config/manifest.json
      - ./keiko_data/log:/keiko/log
      - ./keiko_data/storage:/keiko/storage
    networks:
      - pixelaw
    environment:
      - PUBLIC_NODE_URL=http://localhost:5050
      - PUBLIC_TORII=http://localhost:8080

networks:
  pixelaw:
    driver: bridge

