projectName: pixelaw-core
nameSpace: demo

appType:
  frontend: webapp
  database: db
  api: api

replicaSet: 1

minReplicas: 1
maxReplicas: 1
averageCPUUtilization: 50
averageMemoryUtilization: 50

webappContainerService:
  type: ClusterIP
  port: 3000

katanaContainerService:
  type: ClusterIP
  port: 5050

toriiContainerService:
  type: ClusterIP
  port: 8080

grpcToriiContainerService:
  type: ClusterIP
  port: 50051


domainName: pixelaw.xyz

subDomainName:
  pixelaw: demo
  katana: katana.demo
  torii: torii.demo
  grpcTorii: grpc.demo

dockerImage: ghcr.io/pixelaw/core:latest

worldAddress: "0x1a07a98f25210c7906fc09c44879e09b20b922ba4bf5e8ea5ae48db96f7f4bd"

webapp:
  katanaUrl: "https://api.cartridge.gg/x/pxlw-demo-01/katana"
  toriiUrl: "https://api.cartridge.gg/x/pxlw-demo-01/torii"
  katanaSlotUrl: "https://api.cartridge.gg/x/pxlw-demo-01/katana"
  toriiSlotUrl: "https://api.cartridge.gg/x/pxlw-demo-01/torii"
  seed: "8657283857928754357"
  totalAccounts: "4"

