---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
  labels:
    app: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  replicas: {{ .Values.replicaSet }}
  selector:
    matchLabels:
      app: {{ .Values.projectName }}-{{ .Values.nameSpace }}
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}-{{ .Values.nameSpace }}
    spec:
      containers:
      - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}
        image: {{ .Values.dockerImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.webappContainerService.port }}
        env:
        - name: CORE_VERSION
          value: "{{ .Chart.AppVersion }}"


        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "1000m"

        volumeMounts:
        - name: keiko-storage
          mountPath: /keiko/storage

      volumes:

      - name: keiko-storage
        persistentVolumeClaim:
          claimName: {{ .Values.projectName }}-{{ .Values.nameSpace }}-pvc
