kind = "DojoModel"
class_hash = "0x7974a29051adec721e79e8d6f107df99d710e9d1948684c8daf9459b9117f6e"
original_class_hash = "0x7974a29051adec721e79e8d6f107df99d710e9d1948684c8daf9459b9117f6e"
abi = "manifests/dev/base/abis/models/pixelaw-Area-41f22f17.json"
tag = "pixelaw-Area"
qualified_path = "pixelaw::core::models::area::area"
manifest_name = "pixelaw-Area-41f22f17"

[[members]]
name = "id"
type = "u64"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "default_color"
type = "u32"
key = false
