

# The "Populated" world
# ----------------------------------------------------------------------------
[world]
description = "Empty PixeLAW world"
name = "pixelaw"
seed="pixelaw"

[namespace]
default = "pixelaw"
mappings = { }


[env]
rpc_url = "http://localhost:5050/"
account_address = "0x003c4dd268780ef738920c801edc3a75b6337bc17558c74795b530c0ff502486"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
world_address= "0xf37fcc56c66682b7c2d44f0be6279798820001aeef9ef5d2be8a4b7cea6cd6"
