[world]
description = "PixeLAW world"
name = "pixelaw"
seed = "pixelaw_20241119"

[world.socials]
x = "https://x.com/0xPixeLAW"
github = "https://github.com/pixelaw"


[namespace]
default = "pixelaw"
mappings = {}

[env]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
keystore_path = "accounts/deployer.keystore.json"
account_address = "0x02c306e30b02a1a734bc770af37b32619911f1cfd6ccecb93c5899632f379da9"
#world_address = "0x6f130c8e150882e39cbe878c650c8f35c86579180dbc77d0c1cbe169449b5f6"

[writers]
"pixelaw-App" = ["pixelaw-actions"]
"pixelaw-AppName" = ["pixelaw-actions"]
"pixelaw-AppUser" = ["pixelaw-actions"]
"pixelaw-CoreActionsAddress" = ["pixelaw-actions"]
"pixelaw-Pixel" = [
  "pixelaw-actions",
  "pixelaw-paint_actions",
  "pixelaw-snake_actions",
]
"pixelaw-QueueItem" = ["pixelaw-actions"]
"pixelaw-Snake" = ["pixelaw-actions", "pixelaw-snake_actions"]
"pixelaw-RTree" = ["pixelaw-actions"]
"pixelaw-Area" = ["pixelaw-actions"]
"pixelaw-SnakeSegment" = ["pixelaw-snake_actions"]
