

# The "Empty" world
# ----------------------------------------------------------------------------
[world]
description = "Empty PixeLAW world"
name = "pixelaw"
seed="pixelaw"

[namespace]
default = "pixelaw"
mappings = { }


[env]
rpc_url = "http://localhost:5050/"
account_address = "0x003c4dd268780ef738920c801edc3a75b6337bc17558c74795b530c0ff502486"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
world_address= "0x2c130238b73abf493f1876d26cd52e0f45f318f99accac1d28f0ca6a3d7800f"


## The "Populated" world
## ----------------------------------------------------------------------------
#[profile.dev-pop.tool.dojo.world]
#description = "Populated PixeLAW world"
#name = "dev-pop"
#
#[profile.dev-pop.tool.dojo.env]
#rpc_url = "http://localhost:5050/"
#account_address = "0x003c4dd268780ef738920c801edc3a75b6337bc17558c74795b530c0ff502486"
#private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
#world_address = "0x00a712727a27defbf77122fae30c91e90ec62bba8f09a2a396eddc29b768386b"
