[package]
cairo-version = "=2.7.0-rc.3"
name = "pixelaw"
version = "0.3.35"
homepage = "https://github.com/pixelaw/core"
# Use the prelude with the less imports as possible
# from corelib.
# edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.4" }


[[target.dojo]]
build-external-contracts = [  ]
path = "../contracts/src/lib.cairo"

[tool.dojo]
initializer_class_hash = "0xbeef"

[scripts]
init_auth = "./scripts/init_auth.sh"

# The "Empty" world
# ----------------------------------------------------------------------------
[tool.dojo.world]
description = "Empty PixeLAW world"
name = "pixelaw"
seed="pixelaw"

[tool.dojo.world.namespace]
default = "pixelaw"
mappings = { }


[tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0x003c4dd268780ef738920c801edc3a75b6337bc17558c74795b530c0ff502486"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
world_address= "0xd4136ca2b9f1b08c6d6857b0f19da3dc8d136105ec46459787a6de0fd92bf8"
