[package]
cairo-version = "2.4.0"
name = "pixelaw"
version = "0.0.66"
homepage = "https://github.com/pixelaw/core"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.5.1" }

[[target.dojo]]
build-external-contracts = []

[lib]

[tool.dojo]
initializer_class_hash = "0xbeef"

[scripts]
init_auth = "./scripts/init_auth.sh"
slot_post_deploy = "./scripts/update_scarb.sh &&  ./scripts/init_auth.sh"
slot_deploy = "bash ./scripts/slot_deploy.sh"
post_deploy = "./scripts/update_scarb.sh && ./scripts/update_accounts.sh &&  ./scripts/init_auth.sh && bash ./scripts/upload_manifest.sh"
post_deploy_mac = "./scripts/update_scarb_mac.sh && ./scripts/update_accounts.sh &&  ./scripts/init_auth.sh"
deploy = "sozo build &&  sozo migrate --name pixelaw && ./scripts/update_scarb.sh && ./scripts/update_accounts.sh && ./scripts/init_auth.sh"
deploy_mac = "sozo build &&  sozo migrate --name pixelaw && ./scripts/update_scarb_mac.sh && ./scripts/update_accounts.sh && ./scripts/init_auth.sh"
spawn_pixel_1 = "./scripts/spawn_pixel_1.sh"
put_color_1 = "./scripts/put_color_1.sh"
spawn_rps_1 = "./scripts/spawn_rps_1.sh"
put_rps_1 = "./scripts/put_rps_1.sh"
simple_test = "./scripts/simple_test.sh"
get_2 = "./scripts/get_2.sh"
spawn_pixel_2 = "./scripts/spawn_pixel_2.sh"
put_color_2 = "./scripts/put_color_2.sh"
spawn_rps_2 = "./scripts/spawn_rps_2.sh"
update_accounts = "./scripts/update_accounts.sh"
upload_manifest = "bash ./scripts/upload_manifest.sh"
update_scarb = "bash ./scripts/update_scarb.sh"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
world_address = "0x47864d08a1b86cf0dd52ea2785f8bc93b5f48edca8380bbb3057d158521e12d"

# Default account for katana with seed = 0
account_address = "0x6b86e40118f29ebe393a75469b4d926c7a44c2e2681b6d319520b7c1156d114"
private_key = "0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b"

#keystore_password = "password"
#keystore_path = "../keystore.json"
