[package]
cairo-version = "=2.7.0"
name = "pixelaw"
version = "0.3.40"
homepage = "https://github.com/pixelaw/core"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
#dojo = { git = "https://github.com/dojoengine/dojo", ref = "e42ce0c" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.9" }

[lib]


[profile.dev-pop]

[profile.slot]

[scripts]
init_auth = "./scripts/init_auth.sh"
