[package]
cairo-version = "=2.9.2"
name = "pixelaw"
version = "0.6.0"
homepage = "https://github.com/pixelaw/core"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }
starknet = "2.9.2"

[dev-dependencies]
cairo_test = "2.9.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }

[tool.fmt]
sort-module-level-items = true

[lib]

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]

[features]
default = []

[profile.dev-pop]

[profile.slot]

[profile.sepolia]
