[package]
cairo-version = "=2.9.2"
name = "pixelaw"
version = "0.6.3"
homepage = "https://github.com/pixelaw/core"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }
starknet = "2.9.2"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }

[tool.fmt]
sort-module-level-items = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]

[profile.dev-pop]

[profile.slot]

[profile.sepolia]

[profile.mainnet]

[scripts]
init = "./scripts/init.sh"
paint = "./scripts/paint.sh"
paint_json = "./scripts/paint_json.sh"
populate = "./scripts/populate.sh"
