name: ci-contracts

on:
  push:
    branches: [main]
    paths:
      - "contracts/**"
  pull_request:
    branches: [main]
    paths:
      - "contracts/**"

defaults:
  run:
    working-directory: contracts

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.79.0

jobs:
  cairofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.7.0"
      - run: |
          scarb fmt --check
  dojo-core-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/dojo-dev:e1c9597
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dojo-bins
          path: /tmp/bins
      - uses: actions/checkout@v3
      - run: |
          chmod +x /tmp/bins/sozo
          /tmp/bins/sozo build
          /tmp/bins/sozo test
