kind = "DojoContract"
class_hash = "0x123a3081ef2ee10896770486a01bbb72fc98dbe1d638b11cd0928516e2f4589"
original_class_hash = "0x123a3081ef2ee10896770486a01bbb72fc98dbe1d638b11cd0928516e2f4589"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-actions-16928a49.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-actions"
systems = [
    "init",
    "update_permission",
    "schedule_queue",
    "process_queue",
    "update_pixel",
    "alert_player",
    "set_instruction",
    "remove_area",
]
manifest_name = "pixelaw-actions-16928a49"
